version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8
  build:
    commands:
      - npm install
      - export BUCKET=workflow-1-deployment-artifacts-01
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
#      - aws cloudformation package --template-file template.yaml --output-template-file serverless-output.yaml --s3-bucket aws-chatbot-demo-code

artifacts:
  type: zip
  files:
    - template.yml
 #   - serverless-output.yaml
    - outputtemplate.yml
